### ISSUE TITLE
Polar questions

### ISSUE THREAD

**Issue by joabakk** [ieb/sailinstruments#2]
Great webapp!

I'm trying to make a custom polar, but I'm having difficulty finding it from the app. When installing from npm, there is no `dist/polars/name.json` in the structure. I have stored the new polar in `~/.signalk/resources/polars` but it does not load.

**Comment by ieb** [comment]
The line that loads the polar is https://github.com/ieb/sailinstruments/blob/master/src/components/calcs/performance.js#L66

ie  var url = "polars/"+polarUri+".json";

polarUri being the value of the polarSourceUrl from the global configuration.

If you cant put the json file in  polars/ relative where the webapp is located you should be able to use a setting like ../../../resources/polars/yourpolar  and let the fetch load it. If you look at the javascript console it should tell you a) its trying to load your file and b) what URL its using as it should report an error or 404 when it fails.

I probably need to make this URL an absolute URL rather than the name of the polar file or a relative url.

**Comment by joabakk** [comment]
I made a directory polars under dist, and it shown when I enter the url. I will try with a valid json once the server is back on line (missing brackets around name etc)

**Comment by joabakk** [comment]
It seems to load the default first and then look for the user input polar. No errors:
```Loading default Polar
app.fb656674ad7a6ad9dc9b.bundle.js:1 Starting fine polar build
app.fb656674ad7a6ad9dc9b.bundle.js:1 Finished fine polar build, in SI units
app.fb656674ad7a6ad9dc9b.bundle.js:1 Got new Config  {skinClass: "cs_normal", tabs: Array(2), sourceIdPreferences: Array(1), socket: "default", polarSourceUri: "Kristina-ORC"}
2app.fb656674ad7a6ad9dc9b.bundle.js:1 Saved  layout
```

**Comment by joabakk** [comment]
I noticed an error: ```Form submission canceled because the form is not connected```

**Comment by joabakk** [comment]
```vendor.6edb0b07854c89ff6dfa.bundle.js:1 Uncaught TypeError: this.state.configuringCell.update is not a function at e.value```

**Comment by ieb** [comment]
Should be fixed now.
If you use a value with no / in it, the code assumes that it is a bundled polar file, otherwise it assumes it is a URL. Tested by putting the example polar into /public/examples/testpolar.json and using /examples/testpolar.json as the url. See https://github.com/ieb/sailinstruments/tree/master/src/components/calcs/polar for documentation.

**Comment by joabakk** [comment]
Still struggling. I have created polars under dist, and placed this one under that folder:
 ``` 
{
  "name" : "Kristina-ORC",
  "tws" : [0,4,6,8,10,12,14,16,20,25,30,35,40,45,50,55,60],
  "twa" : [0,5,10,15,20,25,32,36,40,45,52,60,70,80,90,100,110,120,130,140,150,160,170,180],
  "stw" : [
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0.4,0.6,0.8,0.9,1,1,1,1.1,1.1,1.1,1.1,0.1,0.1,0.1,0,0],
[0,0.8,1.2,1.6,1.8,2,2,2.1,2.1,2.2,2.2,2.2,0.5,0.2,0.2,0,0],
[0,1.2,1.8,2.4,2.7,2.9,3,3.1,3.2,3.3,3.3,3.3,1.2,0.5,0.3,0,0],
[0,1.4,2.1,2.7,3.1,3.4,3.5,3.6,3.6,3.7,3.8,3.7,1.7,0.7,0.4,0,0],
[0,1.7,2.5,3.2,3.7,4,4.1,4.3,4.3,4.4,4.5,4.4,2.6,1.1,0.4,0,0],
[0,2.8,4.2,5.4,6.2,6.7,6.9,7.1,7.2,7.4,7.5,7.4,5.6,2.2,0.7,0,0],
[0,3.1,4.7,5.9,6.7,7,7.2,7.4,7.6,7.8,7.9,7.9,6.5,2.6,0.8,0,0],
[0,3.5,5.1,6.3,7,7.3,7.5,7.7,7.9,8.1,8.2,8.3,7.4,2.9,1.2,0,0],
[0,3.8,5.6,6.7,7.3,7.6,7.8,8,8.2,8.4,8.5,8.6,8.2,3,1.3,0,0],
[0,4.2,6,7,7.7,8,8.2,8.3,8.6,8.9,9,9.1,8.9,3.2,1.4,0,0],
[0,4.6,6.3,7.3,8,8.3,8.5,8.7,9,9.3,9.5,9.6,9.6,3.8,1.9,0,0],
[0,4.8,6.6,7.5,8.2,8.6,8.9,9.1,9.5,9.8,10.1,10.4,10.4,4.2,2.1,0,0],
[0,5,6.9,7.9,8.3,8.8,9.2,9.4,9.9,10.4,10.9,11.3,11.3,4.5,2.3,0,0],
[0,5.3,7.1,8.1,8.6,8.9,9.3,9.7,10.4,11.1,11.8,12.5,12.5,5.6,3.1,0.6,0.6],
[0,5.4,7.1,8.2,8.8,9.2,9.5,9.9,10.9,11.9,12.8,14.1,14.1,7.1,4.2,0.7,0.7],
[0,5.3,7,8.1,8.8,9.4,9.8,10.3,11.2,12.7,14.3,15,15,8.3,5.3,1.5,1.5],
[0,5,6.8,7.8,8.6,9.4,10,10.6,11.8,13.2,14.9,15.7,15.7,9.4,6.3,1.6,1.6],
[0,4.5,6.3,7.4,8.3,9,9.8,10.6,12.3,14.4,15.6,16.6,16.6,10.8,7.5,2.5,2.5],
[0,3.8,5.6,6.9,7.8,8.5,9.2,10,12.2,15,16.3,17.6,17.6,13.2,9.7,3.5,2.6],
[0,3.2,4.8,6.1,7.1,7.9,8.6,9.3,10.9,14.4,16.8,18.6,18.6,14.9,11.2,3.7,3.7],
[0,2.7,4.1,5.3,6.4,7.3,8,8.7,10,12.4,15.4,17.9,17.9,15.2,11.6,4.5,3.6],
[0,2.4,3.6,4.8,5.9,6.8,7.6,8.2,9.4,11.4,14.3,16.6,16.6,15.8,12.5,5,4.2],
[0,2.2,3.3,4.4,5.5,6.4,7.2,7.9,9,10.6,12.8,15.4,15.4,15.4,12.3,4.6,3.9]
]
}
```
But I get no errors and the polar still says `undefined`. The reference is polars/kristina.json

**Comment by joabakk** [comment]
![image](https://user-images.githubusercontent.com/2553029/42755300-dfccd7a2-88f7-11e8-8f16-f91fb7496b89.png)

**Comment by ieb** [comment]
try putting the json file somewhere else on the server and using a url starting with /

**Comment by ieb** [comment]
eg 
copied you json into public/examples/Kristina-ORC.json
checked that the URL works
http://localhost:3000/examples/Kristina-ORC.json

Then set the polarSourceUri to /examples/Kristina-ORC.json in SailingInstruments

**Comment by joabakk** [comment]
Sorry to be so slow, which folder is public under? I have an rPi with the node server under ~/.signalk there is no public there anymore. I've tried copying to /usr/lib/node_nodules/signalk-server/public/examples/Kristina-ORC.json. Getting the file via http, but still the same behaviour in sailinstruments

**Comment by ieb** [comment]
It needs to be in a location where the signalk-server is going to serve it from. Typically the signalk-server is installed globally under node js. On my Pi its installed at /usr/local/node, so the signalk-server is installed at /usr/local/node/lib/node_modules/signalk-server and the public examples folder is /usr/local/node/lib/node_modules/signalk-server/public/examples/

Once you have put the file there, check that it can be downloaded using your webbrowser.

There might be a better way of putting a static file onto a signalk server. Someone on Slack may know https://signalk-dev.slack.com/

**Comment by joabakk** [comment]
I can reach it in the browser, but not in the webapp.

**Comment by ieb** [comment]
could you share a screenshot of the javascript console as before and I can compare it against what I have working here.
![screen shot 2018-07-16 at 17 47 31](https://user-images.githubusercontent.com/68709/42771851-683ddb4a-8920-11e8-8e3d-92825d47897e.png)

**Comment by joabakk** [comment]
<img width="1007" alt="skjermbilde 2018-07-17 kl 00 49 37" src="https://user-images.githubusercontent.com/2553029/42787589-67e796b4-895b-11e8-8873-dfa1651f2b73.png">

**Comment by joabakk** [comment]
looks similar

**Comment by joabakk** [comment]
Tried all three browsers, sililar behaviour. IE does not support `endsWith` (see https://www.techcartnow.com/javascript-string-endswith-method-fixing-error-object-does-not-support-property-or-method-endswith-for-not-supported-browsers-ie-10-ie-11/)

**Comment by joabakk** [comment]
Got it working by reinstalling again. I had messed something up, so I wasn't able to load the default either. Thanks for helping out. Looking forward to using the webapp!

**Comment by miquelmp** [comment]
Hello. Congrats for this great app.

I also have a problem with the my polar file. My Raspberry is running Raspbian Stretch. 
I am testing with the file Kristina-ORC.json and sample-nmea0183-data
I have the polar file in /home/pi/.signalk/node_modules/@ib236/sailinstruments/polars/Kristina-ORC.json
I can access to the file with http://raspberrypi:3000/@ib236/sailinstruments/polars/Kristina-ORC.json
![image](https://user-images.githubusercontent.com/49500540/55994144-3d5d4400-5cb1-11e9-8f3a-dd0c46c4d36c.png)

I have the message GET /@ib236/sailinstruments/polars/Kristina-ORC.json 200 7.388 ms - -
![image](https://user-images.githubusercontent.com/49500540/55994191-5c5bd600-5cb1-11e9-8e29-d8033d29f0f8.png)

But I can't get the polar on the webapp
This is my screenshoot, very similar to yours.
![image](https://user-images.githubusercontent.com/49500540/55994031-ea838c80-5cb0-11e9-8244-b4b3ddcf6e05.png)

What am I doing wrong?
