### ISSUE TITLE
Polar file problem

### ISSUE THREAD

**Issue by miquelmp** [ieb/sailinstruments#4]
Hello. Congrats for this great app.

I have a problem with the my polar file. My Raspberry is running Raspbian Stretch, installed from scratch and updated, to test SignalK. I only have installed Raspbian and SignalK with @ib236/sailinstruments.
I am testing with the file Kristina-ORC.json and sample-nmea0183-data
I have the polar file in /home/pi/.signalk/node_modules/@ib236/sailinstruments/polars/Kristina-ORC.json
I can access to the file with http://raspberrypi:3000/@ib236/sailinstruments/polars/Kristina-ORC.json
![image](https://user-images.githubusercontent.com/49500540/55994144-3d5d4400-5cb1-11e9-8f3a-dd0c46c4d36c.png)

I have the message GET /@ib236/sailinstruments/polars/Kristina-ORC.json 200 7.388 ms - -
![image](https://user-images.githubusercontent.com/49500540/55994191-5c5bd600-5cb1-11e9-8e29-d8033d29f0f8.png)

But I can't get the polar on the webapp
This is my screenshoot, very similar to yours.
![image](https://user-images.githubusercontent.com/49500540/55994031-ea838c80-5cb0-11e9-8244-b4b3ddcf6e05.png)

What am I doing wrong?

**Comment by miquelmp** [comment]
I could get the polar files when I connected to real NMEA input data, instead of the sample file.
Should I get the polar with the sample file data?

Congrats again for this project. It's really good.

**Comment by ieb** [comment]
I don't think you were doing anything wrong. The load looks 100% normal and the fine polar build completed. The polar wont show up until it get data for it to draw, and perhap the same file data doesn't have the right data feeds. From memory, it must have tws, twa and stw to display anything.

Sounds like you got it working. If not please re-open. I will look, but I don't get much time between being on the water, and working.
